apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node:18-alpine
        command: ["npm", "start"]
        workingDir: /usr/src/app
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: backend-src
          mountPath: /usr/src/app
      volumes:
      - name: backend-src
        hostPath:
          path: /workspaces/C-Net-Lab/Social-Media-Web-App-Mern-Stack/Server
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
