apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: node:18-alpine
        command: ["npm", "start"]
        workingDir: /usr/src/app
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: frontend-src
          mountPath: /usr/src/app
      volumes:
      - name: frontend-src
        hostPath:
          path: /workspaces/C-Net-Lab/Social-Media-Web-App-Mern-Stack/client
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
