apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-monitor
spec:
  selector:
    matchLabels:
      app: nginx-monitor
  template:
    metadata:
      labels:
        app: nginx-monitor
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
