name: Microservices CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        # Remove the cache option as we'll handle it per service
    
    - name: Test Auth Service
      working-directory: microservices-app/auth-service
      run: |
        npm ci
        npm test
      
    - name: Test Todo Service
      working-directory: microservices-app/todo-service
      run: |
        npm ci
        npm test
    
    - name: Test Frontend
      working-directory: microservices-app/frontend
      run: |
        npm ci
        npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push Auth Service
      uses: docker/build-push-action@v4
      with:
        context: ./microservices-app/auth-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-auth:latest
        build-args: |
          MONGODB_URI=mongodb://${{ secrets.MONGODB_USERNAME }}:${{ secrets.MONGODB_PASSWORD }}@mongo:27017/auth-service
    
    - name: Build and push Todo Service
      uses: docker/build-push-action@v4
      with:
        context: ./microservices-app/todo-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-todo:latest
        build-args: |
          MONGODB_URI=mongodb://${{ secrets.MONGODB_USERNAME }}:${{ secrets.MONGODB_PASSWORD }}@mongo:27017/todo-service
          AUTH_SERVICE_URL=http://auth-service:3001
    
    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./microservices-app/frontend
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-frontend:latest
    
    - name: Build and push Nginx
      uses: docker/build-push-action@v4
      with:
        context: ./microservices-app/nginx
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/microservices-nginx:latest
